# Generated by Django 3.0.8 on 2020-07-05 11:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
