# Generated by Django 3.0.8 on 2020-07-04 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_image_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='instagram.Profile'),
        ),
    ]
