# Generated by Django 3.0.8 on 2020-07-05 22:10

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20200706_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', tinymce.models.HTMLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='comments',
        ),
    ]
