# Generated by Django 3.0.8 on 2020-07-08 09:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20200708_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=tinymce.models.HTMLField(default='Eva'),
            preserve_default=False,
        ),
    ]
